/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class backend_CBackend */

#ifndef _Included_backend_CBackend
#define _Included_backend_CBackend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     backend_CBackend
 * Method:    sRehash0
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_sRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     backend_CBackend
 * Method:    d2sRehash0
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_d2sRehash0
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     backend_CBackend
 * Method:    s2dRehash0
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_s2dRehash0
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     backend_CBackend
 * Method:    dRehash0
 * Signature: (III[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_dRehash0
  (JNIEnv *, jobject, jint, jint, jint, jintArray);

/*
 * Class:     backend_CBackend
 * Method:    mk0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_mk0
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackend
 * Method:    sSize0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_sSize0
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackend
 * Method:    dFetch0
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_backend_CBackend_dFetch0
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackend
 * Method:    add
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_add
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     backend_CBackend
 * Method:    freeze
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_freeze
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackend
 * Method:    readSCuboid0
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_readSCuboid0
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     backend_CBackend
 * Method:    readDCuboid0
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_readDCuboid0
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     backend_CBackend
 * Method:    writeSCuboid0
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_writeSCuboid0
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     backend_CBackend
 * Method:    writeDCuboid0
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_writeDCuboid0
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
