/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class backend_CBackendSecondaryStorage */

#ifndef _Included_backend_CBackendSecondaryStorage
#define _Included_backend_CBackendSecondaryStorage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    reset0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_backend_CBackendSecondaryStorage_reset0
  (JNIEnv *, jobject);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    shhash
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackendSecondaryStorage_shhash
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    sRehash0
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackendSecondaryStorage_sRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    d2sRehash0
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackendSecondaryStorage_d2sRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    s2dRehash0
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackendSecondaryStorage_s2dRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    dRehash0
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackendSecondaryStorage_dRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    rehashToSparse0
 * Signature: (Ljava/lang/String;II[I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackendSecondaryStorage_rehashToSparse0
  (JNIEnv *, jobject, jstring, jint, jint, jintArray);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    mkRandomSecondaryStorage0
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_backend_CBackendSecondaryStorage_mkRandomSecondaryStorage0
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    mkAll0
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackendSecondaryStorage_mkAll0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    mk0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackendSecondaryStorage_mk0
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    sSize0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackendSecondaryStorage_sSize0
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    sNumBytes0
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_backend_CBackendSecondaryStorage_sNumBytes0
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    dFetch0
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_backend_CBackendSecondaryStorage_dFetch0
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    add_i
 * Signature: (III[IJ)V
 */
JNIEXPORT void JNICALL Java_backend_CBackendSecondaryStorage_add_1i
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jlong);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    add
 * Signature: (II[IJ)V
 */
JNIEXPORT void JNICALL Java_backend_CBackendSecondaryStorage_add
  (JNIEnv *, jobject, jint, jint, jintArray, jlong);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    freeze
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackendSecondaryStorage_freeze
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    readSCuboid0
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackendSecondaryStorage_readSCuboid0
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    readDCuboid0
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackendSecondaryStorage_readDCuboid0
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    writeSCuboid0
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackendSecondaryStorage_writeSCuboid0
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    writeDCuboid0
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackendSecondaryStorage_writeDCuboid0
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    readMultiCuboid0
 * Signature: (Ljava/lang/String;[Z[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_backend_CBackendSecondaryStorage_readMultiCuboid0
  (JNIEnv *, jobject, jstring, jbooleanArray, jintArray, jintArray);

/*
 * Class:     backend_CBackendSecondaryStorage
 * Method:    writeMultiCuboid0
 * Signature: (Ljava/lang/String;[Z[I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackendSecondaryStorage_writeMultiCuboid0
  (JNIEnv *, jobject, jstring, jbooleanArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
