/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class backend_CBackend */

#ifndef _Included_backend_CBackend
#define _Included_backend_CBackend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     backend_CBackend
 * Method:    reset0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_reset0
  (JNIEnv *, jobject);

/*
 * Class:     backend_CBackend
 * Method:    shhash
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_shhash
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     backend_CBackend
 * Method:    sRehash0
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_sRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     backend_CBackend
 * Method:    d2sRehash0
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_d2sRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     backend_CBackend
 * Method:    s2dRehash0
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_s2dRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     backend_CBackend
 * Method:    dRehash0
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_dRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     backend_CBackend
 * Method:    saveAsTrie0
 * Signature: ([Lscala/Tuple2;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_saveAsTrie0
  (JNIEnv *, jobject, jobjectArray, jstring, jlong);

/*
 * Class:     backend_CBackend
 * Method:    loadTrie0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_loadTrie0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     backend_CBackend
 * Method:    prepareFromTrie0
 * Signature: ([I)[Lscala/Tuple2;
 */
JNIEXPORT jobjectArray JNICALL Java_backend_CBackend_prepareFromTrie0
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     backend_CBackend
 * Method:    mkAll0
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_mkAll0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     backend_CBackend
 * Method:    mk0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_mk0
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackend
 * Method:    sSize0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_sSize0
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackend
 * Method:    sNumBytes0
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_backend_CBackend_sNumBytes0
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackend
 * Method:    dFetch0
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_backend_CBackend_dFetch0
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackend
 * Method:    cuboidGC0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_cuboidGC0
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackend
 * Method:    add_i
 * Signature: (III[IJ)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_add_1i
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jlong);

/*
 * Class:     backend_CBackend
 * Method:    add
 * Signature: (II[IJ)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_add
  (JNIEnv *, jobject, jint, jint, jintArray, jlong);

/*
 * Class:     backend_CBackend
 * Method:    freezePartial
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_freezePartial
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     backend_CBackend
 * Method:    freeze
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_freeze
  (JNIEnv *, jobject, jint);

/*
 * Class:     backend_CBackend
 * Method:    readSCuboid0
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_readSCuboid0
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     backend_CBackend
 * Method:    readDCuboid0
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_backend_CBackend_readDCuboid0
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     backend_CBackend
 * Method:    writeSCuboid0
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_writeSCuboid0
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     backend_CBackend
 * Method:    writeDCuboid0
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_writeDCuboid0
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     backend_CBackend
 * Method:    readMultiCuboid0
 * Signature: (Ljava/lang/String;[Z[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_backend_CBackend_readMultiCuboid0
  (JNIEnv *, jobject, jstring, jbooleanArray, jintArray, jintArray);

/*
 * Class:     backend_CBackend
 * Method:    writeMultiCuboid0
 * Signature: (Ljava/lang/String;[Z[I)V
 */
JNIEXPORT void JNICALL Java_backend_CBackend_writeMultiCuboid0
  (JNIEnv *, jobject, jstring, jbooleanArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
