/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class backend_RowStoreCBackend */

#ifndef _Included_backend_RowStoreCBackend
#define _Included_backend_RowStoreCBackend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      backend_RowStoreCBackend
 * Method:     reset0
 * Signature:  ()V
 */
JNIEXPORT void JNICALL Java_backend_RowStoreCBackend_reset0
  (JNIEnv *, jobject);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     shhash
 * Signature:  (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_RowStoreCBackend_shhash
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     sRehash0
 * Signature:  (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_RowStoreCBackend_sRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     d2sRehash0
 * Signature:  (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_RowStoreCBackend_d2sRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     s2dRehash0
 * Signature:  (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_RowStoreCBackend_s2dRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     dRehash0
 * Signature:  (I[I)I
 */
JNIEXPORT jint JNICALL Java_backend_RowStoreCBackend_dRehash0
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     sRehashSlice0
 * Signature:  (I[I[Z)[J
 */
JNIEXPORT jlongArray JNICALL Java_backend_RowStoreCBackend_sRehashSlice0
  (JNIEnv *, jobject, jint, jintArray, jbooleanArray);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     dRehashSlice0
 * Signature:  (I[I[Z)[J
 */
JNIEXPORT jlongArray JNICALL Java_backend_RowStoreCBackend_dRehashSlice0
  (JNIEnv *, jobject, jint, jintArray, jbooleanArray);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     saveAsTrie0
 * Signature:  ([Lscala/Tuple2;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_backend_RowStoreCBackend_saveAsTrie0
  (JNIEnv *, jobject, jobjectArray, jstring, jlong);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     loadTrie0
 * Signature:  (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_backend_RowStoreCBackend_loadTrie0
  (JNIEnv *, jobject, jstring);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     prepareFromTrie0
 * Signature:  ([I)[Lscala/Tuple2;
 */
JNIEXPORT jobjectArray JNICALL Java_backend_RowStoreCBackend_prepareFromTrie0
  (JNIEnv *, jobject, jintArray);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     mkAll0
 * Signature:  (II)I
 */
JNIEXPORT jint JNICALL Java_backend_RowStoreCBackend_mkAll0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     mk0
 * Signature:  (I)I
 */
JNIEXPORT jint JNICALL Java_backend_RowStoreCBackend_mk0
  (JNIEnv *, jobject, jint);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     sSize0
 * Signature:  (I)I
 */
JNIEXPORT jint JNICALL Java_backend_RowStoreCBackend_sSize0
  (JNIEnv *, jobject, jint);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     sNumBytes0
 * Signature:  (I)J
 */
JNIEXPORT jlong JNICALL Java_backend_RowStoreCBackend_sNumBytes0
  (JNIEnv *, jobject, jint);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     dFetch0
 * Signature:  (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_backend_RowStoreCBackend_dFetch0
  (JNIEnv *, jobject, jint);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     cuboidGC0
 * Signature:  (I)V
 */
JNIEXPORT void JNICALL Java_backend_RowStoreCBackend_cuboidGC0
  (JNIEnv *, jobject, jint);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     add_1i
 * Signature:  (III[BJ)V
 */
JNIEXPORT void JNICALL Java_backend_RowStoreCBackend_add_1i
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jlong);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     add
 * Signature:  (II[BJ)V
 */
JNIEXPORT void JNICALL Java_backend_RowStoreCBackend_add
  (JNIEnv *, jobject, jint, jint, jbyteArray, jlong);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     freezePartial
 * Signature:  (II)V
 */
JNIEXPORT void JNICALL Java_backend_RowStoreCBackend_freezePartial
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     freeze
 * Signature:  (I)V
 */
JNIEXPORT void JNICALL Java_backend_RowStoreCBackend_freeze
  (JNIEnv *, jobject, jint);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     readMultiCuboid0
 * Signature:  (Ljava/lang/String;[Z[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_backend_RowStoreCBackend_readMultiCuboid0
  (JNIEnv *, jobject, jstring, jbooleanArray, jintArray, jintArray);

/*
 * Class:      backend_RowStoreCBackend
 * Method:     writeMultiCuboid0
 * Signature:  (Ljava/lang/String;[Z[I)V
 */
JNIEXPORT void JNICALL Java_backend_RowStoreCBackend_writeMultiCuboid0
  (JNIEnv *, jobject, jstring, jbooleanArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
